---Unlock fields for editing
SET_ITEM_PROPERTY('EMPLOYEES01.FIRST_NAME', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.LAST_NAME', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.EMAIL', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.PHONE_NUMBER', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.HIRE_DATE', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.JOB_ID', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.SALARY', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.COMMISSION_PCT', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.MAMAGER_ID', UPDATE_ALLOWED, PROPERTY_TRUE);
SET_ITEM_PROPERTY('EMPLOYEES01.DEPARTMENT_ID', UPDATE_ALLOWED, PROPERTY_TRUE);
