--Improve search function 
BEGIN
   IF :CTRL_BLOCK.SEARCHINPUT IS NOT NULL THEN
      SET_BLOCK_PROPERTY('EMPLOYEES01', DEFAULT_WHERE,
         'UPPER(FIRST_NAME) LIKE ''%' || UPPER(:CTRL_BLOCK.SEARCHINPUT) || '%''' ||
         ' OR UPPER(LAST_NAME) LIKE ''%' || UPPER(:CTRL_BLOCK.SEARCHINPUT) || '%''' ||
         ' OR TO_CHAR(EMPLOYEE_ID) = ''' || :CTRL_BLOCK.SEARCHINPUT || '''');
   ELSE
      SET_BLOCK_PROPERTY('EMPLOYEES01', DEFAULT_WHERE, '');
   END IF;

   GO_BLOCK('EMPLOYEES01');
   EXECUTE_QUERY;

   IF :SYSTEM.RECORD_STATUS IS NULL THEN
      MESSAGE('No matching employee found');
      MESSAGE(' ', NO_ACKNOWLEDGE);
   END IF;
END;
